### ISSUE TITLE
Move interests section into content section

### ISSUE THREAD

**Issue by gregthompson27** [isaacsalinas/isaacsalinas.github.io#1]
https://github.com/isaacsalinas/isaacsalinas.github.io/blob/79950823bb6ccd4072038e709253cf9712910c3f/index.html#L33-L41

@isaacsalinas, this interests section is really meant to be nested in the `"content"` div, below the paragraph that says "Student at Salmen High". Make that small change and push your code back up

**Comment by JoshHunter11** [comment]
@gregthompson27  issue resolved
